import { ScanDetailsDto, Severity } from '@surface/shared';

export function generateMarkdownReport(scan: ScanDetailsDto): string {
  const sections: string[] = [];

  sections.push(`# Attack Surface Report`);
  sections.push(`**Target:** ${scan.url}`);
  sections.push(`**Scan ID:** ${scan.id}`);
  sections.push(`**Status:** ${scan.status}`);
  sections.push(`**Created:** ${scan.createdAt}`);
  sections.push(`**Updated:** ${scan.updatedAt}`);
  sections.push(`**Duration:** ${scan.durationMs}ms`);
  sections.push('');

  sections.push(`## Executive Summary`);
  sections.push(`- **Pages discovered:** ${scan.pages.length}`);
  sections.push(`- **Forms extracted:** ${scan.forms.length}`);
  sections.push(`- **Endpoints discovered:** ${scan.endpoints.length}`);
  sections.push(`- **Assets cataloged:** ${scan.assets.length}`);
  sections.push(`- **Risk findings:** ${scan.risks.length}`);
  sections.push(`- **Detected vulnerabilities:** ${scan.risks.filter((r) => r.source === 'DETECTED').length}`);
  sections.push(`- **Technology stack:** ${(scan.techStack || []).join(', ') || 'Unknown'}`);
  sections.push('');

  sections.push(`## OWASP / CWE Risk Mapping`);
  if (scan.risks.length === 0) {
    sections.push('No risks were mapped for this target.');
  } else {
    for (const risk of scan.risks) {
      sections.push(`### ${risk.category} (${risk.severity})`);
      sections.push(`- **OWASP:** ${risk.owasp || 'N/A'}`);
      sections.push(`- **CWE:** ${risk.cwe || 'N/A'}`);
      sections.push(`- **Description:** ${risk.description}`);
      sections.push(`- **Evidence:** ${risk.evidence}`);
      sections.push('');
    }
  }

  const vulnerabilities = scan.risks.filter((r) => r.source === 'DETECTED');
  sections.push(`## Detected Vulnerabilities`);
  if (vulnerabilities.length === 0) {
    sections.push('No vulnerabilities were detected by the passive and active checks.');
  } else {
    for (const vuln of vulnerabilities) {
      sections.push(`### ${vuln.category} (${vuln.severity})`);
      sections.push(`- **Affected URL:** ${vuln.url || 'N/A'}`);
      sections.push(`- **OWASP:** ${vuln.owasp || 'N/A'}`);
      sections.push(`- **CWE:** ${vuln.cwe || 'N/A'}`);
      sections.push(`- **Description:** ${vuln.description}`);
      sections.push(`- **Evidence:** ${vuln.evidence}`);
      sections.push(`- **Remediation:** ${vuln.remediation || 'N/A'}`);
      sections.push('');
    }
  }

  sections.push(`## Pages`);
  for (const page of scan.pages) {
    sections.push(`- [${page.title || 'Untitled'}](${page.url}) — ${page.statusCode || 'unknown status'}`);
  }
  sections.push('');

  sections.push(`## Forms`);
  for (const form of scan.forms) {
    sections.push(`- ${form.method} ${form.action || 'self'} (${form.fields.length} fields)`);
  }
  sections.push('');

  sections.push(`## Endpoints`);
  for (const endpoint of scan.endpoints) {
    sections.push(`- ${endpoint.method || 'GET'} ${endpoint.url} (${endpoint.type})`);
  }
  sections.push('');

  sections.push(`## Assets`);
  for (const asset of scan.assets) {
    sections.push(`- ${asset.type}: ${asset.url}`);
  }
  sections.push('');

  if (scan.errors.length > 0) {
    sections.push(`## Crawler Errors`);
    for (const error of scan.errors) {
      sections.push(`- ${error}`);
    }
  }

  sections.push(`---`);
  sections.push(`*Generated by Attack Surface Discovery Prototype*`);
  return sections.join('\n');
}

export function severityBadge(severity: Severity): string {
  return `**${severity}**`;
}
