import { ScanDetailsDto } from '@surface/shared';

export function buildReportHtml(scan: ScanDetailsDto): string {
  const severityColor: Record<string, string> = {
    CRITICAL: '#ef4444',
    HIGH: '#f97316',
    MEDIUM: '#eab308',
    LOW: '#3b82f6',
    INFO: '#6b7280',
  };

  const riskRows = scan.risks
    .map(
      (r) => `
    <tr>
      <td>${escapeHtml(r.category)}</td>
      <td style="color:${severityColor[r.severity] || '#94a3b8'}">${r.severity}</td>
      <td>${escapeHtml(r.owasp || 'N/A')}</td>
      <td>${escapeHtml(r.cwe || 'N/A')}</td>
      <td>${escapeHtml(r.description)}</td>
      <td>${escapeHtml(r.evidence)}</td>
    </tr>
  `,
    )
    .join('');

  const pageRows = scan.pages
    .map((p) => `<tr><td>${escapeHtml(p.title || 'Untitled')}</td><td>${escapeHtml(p.url)}</td><td>${p.statusCode || '-'}</td></tr>`)
    .join('');

  const endpointRows = scan.endpoints
    .map((e) => `<tr><td>${e.method || 'GET'}</td><td>${escapeHtml(e.url)}</td><td>${e.type}</td></tr>`)
    .join('');

  const assetRows = scan.assets
    .map((a) => `<tr><td>${a.type}</td><td>${escapeHtml(a.url)}</td></tr>`)
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Attack Surface Report — ${escapeHtml(scan.url)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 40px; background: #0f172a; color: #e2e8f0; }
  h1, h2 { color: #f8fafc; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 13px; }
  th, td { border: 1px solid #334155; padding: 8px 12px; text-align: left; vertical-align: top; }
  th { background: #1e293b; color: #94a3b8; }
  tr:nth-child(even) { background: #162032; }
  .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 24px; }
  .card { background: #1e293b; padding: 16px; border-radius: 8px; }
  .card .value { font-size: 24px; font-weight: 700; color: #f8fafc; }
  .card .label { color: #94a3b8; font-size: 12px; }
  .footer { color: #64748b; font-size: 12px; margin-top: 40px; }
</style>
</head>
<body>
  <h1>Attack Surface Report</h1>
  <p><strong>Target:</strong> ${escapeHtml(scan.url)}<br>
     <strong>Scan ID:</strong> ${escapeHtml(scan.id)}<br>
     <strong>Status:</strong> ${scan.status}<br>
     <strong>Created:</strong> ${scan.createdAt}<br>
     <strong>Duration:</strong> ${scan.durationMs}ms</p>

  <h2>Executive Summary</h2>
  <div class="summary">
    <div class="card"><div class="value">${scan.pages.length}</div><div class="label">Pages</div></div>
    <div class="card"><div class="value">${scan.forms.length}</div><div class="label">Forms</div></div>
    <div class="card"><div class="value">${scan.endpoints.length}</div><div class="label">Endpoints</div></div>
    <div class="card"><div class="value">${scan.assets.length}</div><div class="label">Assets</div></div>
  </div>

  <h2>Risk Findings</h2>
  <table>
    <thead><tr><th>Category</th><th>Severity</th><th>OWASP</th><th>CWE</th><th>Description</th><th>Evidence</th></tr></thead>
    <tbody>${riskRows || '<tr><td colspan="6">No risks mapped.</td></tr>'}</tbody>
  </table>

  <h2>Pages</h2>
  <table>
    <thead><tr><th>Title</th><th>URL</th><th>Status</th></tr></thead>
    <tbody>${pageRows || '<tr><td colspan="3">No pages discovered.</td></tr>'}</tbody>
  </table>

  <h2>Endpoints</h2>
  <table>
    <thead><tr><th>Method</th><th>URL</th><th>Type</th></tr></thead>
    <tbody>${endpointRows || '<tr><td colspan="3">No endpoints discovered.</td></tr>'}</tbody>
  </table>

  <h2>Assets</h2>
  <table>
    <thead><tr><th>Type</th><th>URL</th></tr></thead>
    <tbody>${assetRows || '<tr><td colspan="2">No assets cataloged.</td></tr>'}</tbody>
  </table>

  <div class="footer">Generated by Attack Surface Discovery Prototype</div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
